### ISSUE TITLE
`_check_parent_dir_exists` documentation

### ISSUE THREAD

**Issue by SergioRec** [datasciencecampus/transport-network-performance#103]
Function `_check_parent_dir_exists`, in `transport_performance/utils/defence.py` needs documentation. Behaviour is not as I'd expect: it will get the parent directory of whatever path is fed into the function, so if called like this, it will not throw any error even though the directory does not exist:

```
path1 = os.path.join(here(), 'no_folder')
_check_parent_dir_exists(path1, 'n', create=False)
```

It will however throw an error if something else was appended to the path:
```
path2 = os.path.join(here(), 'no_folder//no_file.txt')
_check_parent_dir_exists(path2, 'n', create=False)
```

**Comment by cbrowning04** [comment]
Hi @SergioRec. Essentially the function is only checking if the parent of the specified path exists. In your example, the parent would be here() where as 'no_folder' would be regarded as simply the file. Therefore it would conclude that here() already exists. In the second example, 'no_folder' in the path would be regarded as the parent directory. As this does not exist, an error is thrown.  

I'll update the documentation to better explain this.
