### ISSUE TITLE
Update package wide testing to pass pathlib.Path({path}) to tests rather than strings

### ISSUE THREAD

**Issue by cbrowning04** [datasciencecampus/transport-network-performance#114]
## Describe the bug

Since the recent updates to `check_parent_dir_exists()`, paths can no longer be passed as strings. Strings include paths generated by os.path operations. This is because on a windows machine, these paths include back slashes (\), which aren't accepted by `check_parent_dir_exists()`. Because of this, many tests fail.

## Environment

OS: Windows 10
Python version: 3.9.13
Java version: N/A
Python module versions (if different from requirements.txt):

## Screenshots  

![Image](https://user-images.githubusercontent.com/121952297/264746874-520e0743-3309-49e0-8281-7995d473a654.png)

**Comment by ethan-moss** [comment]
Closed during #117.
