### ISSUE TITLE
invalid route type caveat

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#130]
**Description of the Feature to be Added**

For route type == 200, can we include some text at the top, explaining that the message from gtfs_kit is not helpful, and that the route_type 200 is part of the proposed extended schema that they do not recognise? I think it’s worth doing though not super urgent as anyone using this is likely to encounter this route type in their GTFS.

**(OPTIONAL) Suggested Implementations**

some text at the top of the table when the issue is about route type 200 (coaches)

**Additional context**

<img width="1028" alt="image" src="https://github.com/datasciencecampus/transport-network-performance/assets/49126943/64df297c-b2fb-43d8-b314-6ba074283d27">

**Comment by cbrowning04** [comment]
@r-leyshon I we thinking that we could add a cleaner to the cleaners module (once it's merged into dev) that cross references the 'invalid' route types with our extended route type table. Does this sound good to you?

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/22
