### ISSUE TITLE
Check tables in each GTFS file and verify them

### ISSUE THREAD

**Issue by cbrowning04** [datasciencecampus/transport-network-performance#134]
I can think of 2 other conditions we would want to check for raise:

1. Fewer files than expected
2. Additional files than expected (perhaps a warning is more appropriate here if we can test it without having it show up in test reports)

As logic not implemented, this can be a feature request. Would you agree?

_Originally posted by @r-leyshon in https://github.com/datasciencecampus/transport-network-performance/pull/112#discussion_r1325958601_

**Comment by cbrowning04** [comment]
### Discovery  
It appears that `gtfs-kit` will only read in tables that are included the the following dictionary. 
![image](https://github.com/datasciencecampus/transport-network-performance/assets/121952297/5af26536-2983-45a5-b5cd-2fb300f8c3b7)
It will however not raise any errors or notifications, informing the user that it has not read this table, or that it even exists.  

On the other hand, `gtfs-kit` will notify the user if one of the required tables are missing, This will appear in the table returned through `feed.validation`.

### Recommendation
In this case, I recommend that we wait for the cleaners/validation modules to be merged with dev and then alert the user in the validation table of the invalid table that isn't being read as part of the GTFS feed.

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/7
