### ISSUE TITLE
standardise defensive checks in GTFS module

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#157]
**Description of the Feature to be Added**

GTFS module needs to be brought up to speed with changes in utils.defence. Standardising the use of these utilities and removing some duplicated type checks, associated refactoring of tests will be needed.

**(OPTIONAL) Suggested Implementations**

**Additional context**

**Comment by ethan-moss** [comment]
Duplicate of #152, so closing.
