### ISSUE TITLE
Find urban centres

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#16]
**Description of the Feature to be Added**

- [x] Finding urban centre from fixed coordinate
- [x] Implementing urban centre logic
- [x] Implement buffering around urban centre

**Comment by SergioRec** [comment]
Main functions done. To do next:

- [ ] 3 outputs: urban centre gdf, buffer boundaries gdf and bbox (`.bounds` method on buffer).
- [ ] Wrap functions / class.
- [ ] Write unit tests.

Opened new ticket for next sprint, closing this.
