### ISSUE TITLE
Update the urban centres module to utilise defence.py

### ISSUE THREAD

**Issue by cbrowning04** [datasciencecampus/transport-network-performance#160]
**Description of the Feature to be Added**

The urban centres module includes many defences that don't utilise the functions in `defency.py`. This module should be brought in line with the rest of the package by implementing the defence functions.

**(OPTIONAL) Suggested Implementations**

**Additional context**

**Comment by ethan-moss** [comment]
@CBROWN-ONS - Thanks for raising this! The population module was updated to utilise `defence.py` functions in #144. Does this issue perhaps relate to a different module that needs updating?

**Comment by cbrowning04** [comment]
Good spot. This was meant to be urban centres sorry. I'll update accordingly

**Comment by ethan-moss** [comment]
That's OK, no worries! Just thought I'd check in case #144 had missed something 👍 Thanks!
