### ISSUE TITLE
Replace defences in `urban_centres` with `utils.defence` functions.

### ISSUE THREAD

**Issue by SergioRec** [datasciencecampus/transport-network-performance#168]
**Description of the Feature to be Added**
Some defences in the `urban_centres` module should be replaced with  `utils.defence` functions.

**(OPTIONAL) Suggested Implementations**

**Additional context**

**Comment by cbrowning04** [comment]
Would you say this is a copy of #160 @SergioRec ?

**Comment by SergioRec** [comment]
Sorry, didn't see you had created an issue already. Closing as duplicate.
