### ISSUE TITLE
gtfs validation additional features

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#18]
**Description of the Feature to be Added**

 - [ ]  % / n services by mode on a given day of interest (Could)
 - [ ] Distribution of services by mode across all available dates (Wont)
 - [ ]  Compare day of interest service to GTFS distribution (Wont)
 - [ ]  HTML output (Wont)

**Comment by cbrowning04** [comment]
Hi @r-leyshon. I'm currently working on 'HTML output (Wont)' but it won't be fully finished until atleast the week commencing 21st of August.  
In regards to the other tasks, would you say  'Distribution of services by mode across all available dates (Wont)' and
'Compare day of interest service to GTFS distribution (Wont)' are complete under `summarise_routes()` and `summarise_trips()` or are we looking to more specifically target `service_id` in the GTFS data?

**Comment by ethan-moss** [comment]
Closing since these are already features in the `GTFS` module and the html outputs additions.
