### ISSUE TITLE
gtfs `clean_feed()` pipeline

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#181]
**Description of the Feature to be Added**

The sequence of GTFS cleaning steps is highly dependent on both ordering requirements and user needs. An ability to flexibly map GTFS cleaning steps to a user's request would be useful feature to give flexibility and control over cleaning methods.

**(OPTIONAL) Suggested Implementations**

A list of dicts could be used, where keys are the cleaning function and values are another dict corresponding to argument/value pairs for the cleaning functions, e.g.:

```python
gtfs_clean_pipeline = [
	{
		"clean_multiple_stop_fast_travel_warnings": {
			"max_distance": 10,
			...
		}
	},
	{
		"clean_consecutive_stop_fast_travel_warnings": {
			...
		}
	},
	...
]
```

**Additional context**

Feature request raising from PR #125

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/11
