### ISSUE TITLE
rename bbox_filter_gtfs

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#204]
**Description of the Feature to be Added**

The function now offers date filtering. Better to make consistent with the OSM module `filter_osm` function.

**(OPTIONAL) Suggested Implementations**

**Additional context**

**Comment by cbrowning04** [comment]
@r-leyshon Just to clarify, I'll be implementing this in my own branch (multi-gtfs-validation) and you weren't planning on implementing elsewhere? Just making sure we both have the same idea.

**Comment by r-leyshon** [comment]
All good, thanks for picking it up.
