### ISSUE TITLE
pytest CI fail: 'CallSpec2' object has no attribute 'funcargs'

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#244]
**Describe the bug**

Prior passing runs were with pytest-7.4.4. Current failing runs are with pytest 8.0.0. Pin pytest version to avoid this.

[pytest-8.0.0](https://github.com/pytest-dev/pytest/releases/tag/8.0.0) was released 27th Jan.

**Comment by hzheng23** [comment]
Same problem in pytest 8.2.0, I fixed by downgrade pytest to 7.4.4
