### ISSUE TITLE
update setup info

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#4]
**Describe the bug**

`README.md` has no set-up information/guidance meaning it's more difficult for users to work with the code base.

**Environment**

 - OS: macos
 - Python version: N/A
 - Java version: N/A
 - Python module versions (if different from `requirements.txt`): Does this mean if different from reqs.txt in main branch? As in we're adjusting the deps?

**Additional context**

A quickstart guide to setting up for working with r5 on macos. 

### Acceptance Criteria

- [ ] Guidance captures necessary setup instructions on macos
- [ ] Included within a section in readme
- [ ] Can be followed to setup a new environment

***

### Epic

Undefined at this moment.

### Dependencies

This is a child of [#heimdall#2](https://github.com/datasciencecampus/heimdall)

**Comment by r-leyshon** [comment]
Am picking this up as a bite-size piece following the supplementary reading.
