### ISSUE TITLE
Help users create valid `aoi_bounds` Polygon

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#51]
`aoi_bounds` - the `population.ipynb` was enough for me to reproduce a valid input based on the `GHSL_2020_merged_200.tif`. Case to include a fixture and example implementation in the docstring. Example usage, possibly in the pipelines folder? Maybe some test data. Agreed to raise as  feature request.

_Originally posted by @r-leyshon in https://github.com/datasciencecampus/transport-network-performance/pull/44#discussion_r1288557212_

**Comment by ethan-moss** [comment]
We can close this ticket since we can now pass in an urban centre boundary/buffer into the module. Example will be part of the main documentation completion.
