### ISSUE TITLE
defence utility check polygon

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#54]
Occurs to me that this snippet would be a useful utility function. Agreed to raise as technical debt issue.

_Originally posted by @r-leyshon in https://github.com/datasciencecampus/transport-network-performance/pull/44#discussion_r1288578166_

**Comment by ethan-moss** [comment]
This issue needs to be broadened to ensure `defence.py` functions are used throughout `RasterPop`.
