### ISSUE TITLE
assertion failure messages where possible

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#56]
**Description of the Feature to be Added**

Helpful in diagnosing the source of breaking changes and the expected behaviours.

**(OPTIONAL) Suggested Implementations**

**Additional context**

Agreed that this is not always possible in cases where `pd.testing` is used for example, frame assert equal doesn't seem to allow for this. But in cases of regular `assert` we should be including these.

**Comment by ethan-moss** [comment]
A resolution has been incorporated as part of 54-56-population-defence branch. It wasn't an original intention, but bringing the `population` module up to date with `defence.py` has resolved the issue.
