### ISSUE TITLE
Change default unit argument from "m" to "km"

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#63]
**Description of the Feature to be Added**

The `GtfsInstance` class has a default argument of "m" for the GTFS units. However, this is not very common - "km" is more widely adopted and would be a better choice as the default argument to help protect against potential unforeseen errors.

**(OPTIONAL) Suggested Implementations**

Change the default unit argument from "m" to "km" throughout the class.

**Additional context**

Examples of Km units being used can be provided if needed.

**Comment by ethan-moss** [comment]
Closing since performance gains would be too minor and unable to trust the stability of the end point.

**Comment by r-leyshon** [comment]
Reopening as realised this was not completed with #143 (my mistake, that resolved the default units value in the OSM module, not GTFS).
