### ISSUE TITLE
optional arg for `viz_stops()` to only plot `stop_id`'s in `stop_times.txt`

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#70]
**Description of the Feature to be Added**

Add an optional argument to the [`viz_stops()`](https://github.com/datasciencecampus/transport-network-performance/blob/dev/src/transport_performance/gtfs/validation.py#L173), used when `geom="points"`, to only plot `stop_id`'s in `stop_times.txt`. 

This will correspond to the case where the stops are parts of trips within the GTFS data. Currently, it plots all stops in `stops.txt` regardless of whether or not they are references in `stop_times.txt`. This means stops with location_types not `nan` or `0` are also being visualised (e.g. stations, entrances/exits etc.). See the [GTFS spec for `stops.txt`](https://developers.google.com/transit/gtfs/reference#stopstxt) for more details.

**(OPTIONAL) Suggested Implementations**

Use optional argument to create a unique set of stops from `stops.txt` if and only if they are in `stop_times.txt`. This can be achieved by passing `feed.stops[feed.stops.stop_id.isin(feed.stop_times.stop_id.unique)].stop_id.to_list()` into the plotting function when the optional argument is given.

**Comment by r-leyshon** [comment]
@ethan-moss I've implemented this feature ([please see here](https://github.com/datasciencecampus/transport-network-performance/tree/70-optional-arg-for-viz_stops-to-only-plot-stop_ids-in-stop_timestxt)). 

Haven't raised PR yet, as I think we may want to go further. The patch in the link above is minimal (just the param and some light refactoring to avoid complexity hook, standardise with _type_defence and update test assertions).

My idea for further work would be:
* If we have filtered the GTFS using gtfs_kit, should we have `bbox_filter_gtfs` drop rows in stops.txt that do not appear in stop_times.txt? 
* Doing so would make the visuals for stop points and hull consistent. 
* Without doing so, the hull visual still calculates from stops.txt and you get the larger boundary.
* Implementing this behaviour could be optional, but it would likely render the implementation here defunct.

<img width="1778" alt="image" src="https://github.com/datasciencecampus/transport-network-performance/assets/49126943/2d52c185-2974-4ec5-beaf-7f1576e4e54d">


Can you think of any potential negative to dropping stop IDs in stops.txt that are not referenced in stop_times.txt?

**Comment by ethan-moss** [comment]
Nice one @r-leyshon!

I don't think there are any major negatives in doing that, at least from a practical/analysis side. Keeping them in shouldn't impact the analysis of the transport network since they aren't used in trips.

The only negatives I can think of relate more to GTFS exploration/validation. In particular, exploring stops_ids associated with records that aren't 'physical stops' used in trips. These would be things like stations, stations entrances/exits, boarding areas etc. (any records in `stops.txt` that have a `location_type` that is not 0 or empty). It could be possible that a user may wish to:
- Include these in the visuals (to see what other stop location types exist in the data prior to cleaning)
- Get information about a parent station for a stop (e.g. to check what station a stop resides in - assuming that id is stored in `parent_station`).
> I wouldn't say either of these points are the main purpose of `viz_stops()` though, perhaps they are nice to haves?

Maybe we could generalise the `viz_stops()` function to capture these cases? Perhaps by adding an argument to be able to visualise 1) all the stops in `stops.txt` (as-is), 2) only stop_ids that appear in `stop_times.txt` (the new addition as part of this ticket and shown above), and 3) take a list of `location_types` the user would like to visualise. What do you think? That way, we have all bases covered.

If we were to drop them as part of the cleaning stage, perhaps we could build this in as an optional cleaning step? I'd see it more as 'tidying' as opposed to necessary cleaning/fixing of a validation issue. What do you think? If you agree, we would need to write our own cleaner. `gtfs_kit`'s `drop_zombies()` function (which is part of `clean_feed()`) drops stops of location type 0 or enmpth that have no stop times in `stop_times.txt`, and removes undefined parent stations from the parent_station column, but does not remove parents themselves (according to [the function docs](https://mrcagney.github.io/gtfs_kit_docs/#gtfs_kit.cleaners.drop_zombies)). So we'd need to do this last bit ourselves.

**Comment by r-leyshon** [comment]
OK great, I've implemented it so that asking for `GtfsInstance.viz_stops(... filtered_only=True)` (the default) will plot the stop_times subset, whether you're asking for points or the hull. But this will not drop any rows from the stops table attribute. Though it would be straight forward to implement such a thing if needed in the future.

Behaviour now looks like:
```
>>> self.viz_stops("foobar.html")
>>> self.viz_stops("foo.html", geoms="hull")
```

<img width="1792" alt="image" src="https://github.com/datasciencecampus/transport-network-performance/assets/49126943/218c6225-5160-401d-97d2-b22b6a774e35">


And asking for no filtering:
```
>>> self.viz_stops("foobar.html", filtered_only=False)
>>> self.viz_stops("foo.html", geoms="hull", filtered_only=False)
```
<img width="1782" alt="image" src="https://github.com/datasciencecampus/transport-network-performance/assets/49126943/c1c1a375-194f-4a42-93aa-57b32983557e">
