### ISSUE TITLE
Open `bbox_filter_gtfs()` bbox to be a polygon

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#71]
**Description of the Feature to be Added**

Open [`bbox_filter_gtfs()`](https://github.com/datasciencecampus/transport-network-performance/blob/dev/src/transport_performance/gtfs/utils.py#L10) bbox to be a polygon instead of a list:
- GTFS kit docs suggest the [`restrict_to_area()` method](https://mrcagney.gitlab.io/gtfs_kit_docs/index.html#gtfs_kit.miscellany.restrict_to_area) accepts a gdf of polygons. So we could open up this function to accept a polygon as an input (instead of a BBOX). This would then be the same input type as the `RasterPop` module.
- This would also the work better with the `urban_centre` module, which returns `shapely` polygons.

**Comment by r-leyshon** [comment]
Sounds like a useful feature @ethan-moss , though could we have a list or a polygon? Common pattern of mine is to pull a bbox csv of klokantech etc and paste it into a list.
