### ISSUE TITLE
develop `gtfs` cleaner for `Unrecognised column` warnings

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#72]
**Description of the Feature to be Added**

`Unrecognised column` warnings are commonly raised by the `is_valid()` method, but are not resolved by cleaning. 

E.g. `Unrecognized column agency_noc` and `Unrecognized column vehicle_journey_code` are regularly raised when working with GTFS data extracted from DfT's BODS. These columns have nothing to do with the GTFS spec and can be safely removed from the feed (NOC is National Operator Code and journey_code is used by DfT to describe the bus type).

**(OPTIONAL) Suggested Implementations**

Add an extra optional argument to `clean_feed()` which accepts a lists of columns to drop. For each column provided, these can then be removed from and feed dataframe if the column is present. Giving the user the ability to define which ones can be removed safely is important here, since `gtfs_kit` doesn't handle the extended GTFS definitions and so dropping all unrecognised columns could lead to issues.

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/4
