### ISSUE TITLE
develop `gtfs` cleaner to handle `repeated pair (trip_id, departure_time)` warnings

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#73]
**Description of the Feature to be Added**

Calling `is_valid()` regularly leads to `repeated pair (trip_id, departure_time)` in `stop_times.txt` but these are not cleaned by `clean_feed()`. Further investigation shows that:
- typically this is because neighbouring rows in `stop_times.txt`, within a given trip, have duplicate trip_id, arrival_time, departure_time, and stop_id. It's clear this circumstance is an erroneous duplication.
- less often, there are neighbouring stops very close together, but they have different `stop_ids` - it's possible for these to be timetabled with the same time because of their proximity. Here is an example where a bus turns around and serves two stops on either side of the road (near Dingestow):
![Screenshot 2023-08-14 at 18 35 05](https://github.com/datasciencecampus/transport-network-performance/assets/106239610/8f25424b-af97-4bed-93f4-93a1dde0959c)

**(OPTIONAL) Suggested Implementations**

In `stop_times.txt`, when records have duplicate trip_id, arrival_time, departure_time, and stop_id these can be safely dropped (represent the same trip, stop and time). Develop a clean which drops these from the stop_times feed, to prevent these warnings from remaining.

**Additional context**

**Comment by r-leyshon** [comment]
@ethan-moss 
 I need help in understanding the issue:
```
1	typically this is because neighbouring rows in stop_times.txt, within a given trip, have duplicate trip_id,
arrival_time, departure_time, and stop_id. It's clear this circumstance is an erroneous duplication.

2	less often, there are neighbouring stops very close together, but they have different stop_ids - it's possible for
these to be timetabled with the same time because of their proximity. Here is an example where a bus turns around
and serves two stops on either side of the road (near Dingestow):

```
Point 1 seems straight forward - whenever consecutive trips have the same trip_id, arrival_time, departure_time, and stop_id, drop the duplicate.

Point 2 - I am uncertain if it asks for any intervention. 2 different stops that are very close together and have the same arrival / departure time (not specified above). As these have different stop_ids they would not qualify for cleaning in point 1. Therefore I am uncertain as to whether this point calls for any treatment. Could you let me know if I have misunderstood the ask?

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/5
