### ISSUE TITLE
Improve `clean_feed()` when shape_id not available

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#74]
**Description of the Feature to be Added**

`clean_feed()` is a shallow wrapper around `gtfs_kit`'s `clean()` function which implements 4 cleaning functions:
1. `clean_ids()`: strip whitespace from all string IDs and then replace every remaining whitespace chunk with an underscore
2. `clean_times()`: convert H:MM:SS time strings to HH:MM:SS time strings to make sorting by time work as expected.
3. `clean_route_short_names()`: In `feed.routes`, assign ‘n/a’ to missing route short names and strip whitespace from route short names. Then disambiguate each route short name that is duplicated by appending ‘-’ and its route ID. Note: this is the method that fixes the "Repeated pair (route_short_name, route_long_name)" warning. 
4. `drop_zombies()`: does the following:
    - Drop stops of location type 0 or NaN with no stop times.
    - Remove undefined parent stations from the parent_station column.
    - Drop trips with no stop times.
    - Drop shapes with no trips.
    - Drop routes with no trips.
    - Drop services with no trips.

`clean_feed()` and hence `clean()` will fail if there is no `shape_id` column in `trip.txt`. However, `drop_zombies()` is the only one that relies on that column, the 3 other cleaning functions work fine:
![Screenshot 2023-08-15 at 10 57 39](https://github.com/datasciencecampus/transport-network-performance/assets/106239610/c0f3e83d-06e1-4995-8b5b-2431f37afac6)

**(OPTIONAL) Suggested Implementations**

Instead of returning without cleaning if `shape_id` is not present, this could be improved to instead only action the first 3 cleaning methods.

**Comment by cbrowning04** [comment]
Note to self:
To replicate error, delete `shape_id` from `feed.trips`

**Comment by cbrowning04** [comment]
### UPDATE
This issue will not be completed before the end of sprint 4 due to it relying on other PRs that are yet to be merged. This issue _should_ however be completed early on in sprint 5.

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/6
