### ISSUE TITLE
implement `gtfs` validation check on fast travel between stops

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#77]
**Description of the Feature to be Added**

`gtfs_kit` does not currently implement any sense checking/validation against scenarios where GTFS timetabling is unfeasible. In particular, there are circumstances when the timetabled time to travel consecutive stops is way too small such that the transit vehicle would need to travel at impossible speeds. This can happen when the trip is poorly timetabled/designed, the arrival/departure time is incorrect/erroneous or when the stop location is erroneous. 

Some examples of these behaviours includes, these 3 consecutive stops (which is >1hr trip in real life), but should only take 8 minutes to get between stop 1 and 3.:
![Screenshot 2023-08-14 at 19 02 44](https://github.com/datasciencecampus/transport-network-performance/assets/106239610/0d416695-7509-4447-9c7f-32901fe81cbd)

Also, there are some trips which include erroneous stops, e.g. in the middle of the sea:
![Screenshot 2023-08-14 at 19 08 16](https://github.com/datasciencecampus/transport-network-performance/assets/106239610/32fcbf8b-f675-41de-8ead-06d570fff7f0)

In all these cases, it could severely impact the transport performance metrics that are based on these unrealistic trips. So, a validation function is required to catch these cases.

**(OPTIONAL) Suggested Implementations**

Longer term solution: explore feasibility of replacing `gtfs_kit` with [`gtfs-validator`](https://github.com/MobilityData/gtfs-validator), an open-source java based GTFS validation tool. It maybe possible to develop a python wrapper to integrate it into this pipeline. It contains validation checks for these sorts of stop anomalies, however `gtfs_kit` has additional validation checks that `gtfs-validator` doe not (such as Repeated pair (route_short_name, route_long_name), unknown columns, and repeated pair (trip_id, departure time)) - so it's not a straight forward swap as it doesn't provide all the functionalities needed.

Shorter term solution: we could re-implement stop validation checks in python (all credit for these methodologies go to the [`gtfs-validator`](https://github.com/MobilityData/gtfs-validator) developers) : 

1. `validate_travel_between_consecuitve_stops()`:
- Calculates the distance between neighbouring stops as the crow flies.
- Use the arrival and departure time to get the trip time.
- Estimate the speed using the above 2 points.
- Threshold speed based on modality.

2. `validate_travel_over_multiple_stops()`:
- As above, but considers travel between multiple stops and averages transit speed over them - this has the advantage of picking out more significant errors since the unrealistic speeds would need to be maintained for much larger distances. In practice, these trips may need to be physically dropped from the GTFS file before analysis (this may warrent the development of another cleaner method since `gtfs_kit` doesn't seem to have a 'drop trip' method).

Prototype functions have already been developed and trialled locally, for both `validate_travel_between_consecuitve_stops()` and `validate_travel_over_multiple_stops()` - seem to be running well. These would need further work/refactoring, testing and integration into the the `gtfs` module as additional validation functions.

**Comment by cbrowning04** [comment]
@ethan-moss Could you share some of the prototypes here so that they can be understood/built upon? Thanks
