### ISSUE TITLE
Unclear error message by function `is_expected_filetype()` in `transport_performance/utils/defence.py`

### ISSUE THREAD

**Issue by SergioRec** [datasciencecampus/transport-network-performance#83]
**Description of the Feature to be Added**
The following error message from function [`is_expected_filetype()`](https://github.com/datasciencecampus/transport-network-performance/pull/34/files#diff-1db0a33e64c257006c83f9bef89b75a91fd62f2aa0f5b7729b6dbe517628ca49) is unclear.
```
>>> filter_osm(pbf_pth = 'folder/subfolder/blah.pbf')
FileExistsError: folder/subfolder/blah.pbf not found on file.
```

Something like `<file> not found` would read better.

**Comment by ethan-moss** [comment]
Closed by #108.
